Logging 1
Otus-DevOps-2021-11/vicha2_microservices pull request #5
Opened 2022-03-21 15:14 UTC by vicha2

# Выполнено ДЗ № Не выполнено!!! В Kibana индексы так и не появились.

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-03-22 07:12 UTC, mrgreyves reviewed
Здравствуйте!)
Пока что пускай повисит ваш пуллреквест
Закрывать его не стоит
В слаке отписался куда стоит посмотреть =)

2022-03-29 09:06 UTC, mrgreyves requested changes
Здравствуйте!)
Добавил мини-методичку по работе с эластиком и флуентд
Теперь можно пофиксить эту историю с индексом и данными

2022-04-03 17:33 UTC, vicha2 commented
@mrgreyves , добрый день.
Необходимые правки выполнены, спасибо, все заработало!

2022-04-04 14:44 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув!=)

2022-04-04 15:37 UTC, merged